language: haskell
ghc: 7.8
before_install:
 - sudo sed -i -e 's/precise/trusty/' /etc/apt/sources.list
 - sudo apt-get update -qq
 - sudo apt-get install -qq libusb-1.0-0-dev
 - cabal install bindings-libusb==1.4.5.0
